appName: qbittorrent
imageLocation: lscr.io/linuxserver/qbittorrent:latest
containerPorts: 
  - name: web-ui
    port: 30900
    targetPort: 30900
    nodePort: 30900
    protocol: TCP
  - name: torrenting
    port: 30681
    targetPort: 30681
    nodePort: 30681
  - name: torrenting-udp
    port: 30681
    targetPort: 30681
    nodePort: 30681
    protocol: UDP
ingress:
  enabled: true
  servicePort: 30900
gluetun:
  enabled: true
  volumeName: media
envVars:
  TZ: America/Toronto
  PUID: 1000
  PGID: 1000
  WEBUI_PORT: 30900
existingVolumes:
  - name: 'media'
    claimName: 'download-volume-claim'
existingVolumeClaims:
  - name: 'media'
    mountPath: '/media/torrents'
    subPath: 'torrents'
  - name: 'media'
    mountPath: '/config'
    subPath: 'configs/qbittorrent'
