appName: prowlarr
imageLocation: lscr.io/linuxserver/prowlarr:latest
containerPorts: 
  - name: web-ui
    port: 9696
    targetPort: 9696
    nodePort: 30969
    protocol: TCP
ingress:
  enabled: true
  servicePort: 9696
gluetun:
  enabled: false
  volumeName: media
envVars:
  TZ: America/Toronto
  PUID: 1000
  PGID: 1000
existingVolumes:
  - name: 'media'
    claimName: 'download-volume-claim'
existingVolumeClaims:
  - name: 'media'
    mountPath: '/config'
    subPath: 'configs/prowlarr'