---
# Source: media-server-chart/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: media-server
---
# Source: media-server-chart/templates/download-volume.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: download-volume
  namespace: media-server
  labels:
    type: local
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/external-media/media"
---
# Source: media-server-chart/templates/download-volume-claim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: download-volume-claim
  namespace: media-server
spec:
  storageClassName: manual
  volumeName: download-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
# Source: media-server-chart/charts/bazarr-chart/templates/everything.yaml
apiVersion: v1
kind: Service
metadata:
  name: media-server-bazarr-service
  namespace: media-server
spec:
  type: NodePort
  selector:
    app: media-server-bazarr-template
  ports:
    - name: web-ui
      port: 6767
      targetPort: 6767
      
      protocol: TCP
      
      nodePort: 30676
---
# Source: media-server-chart/charts/calibre-web-chart/templates/everything.yaml
apiVersion: v1
kind: Service
metadata:
  name: media-server-calibre-web-service
  namespace: media-server
spec:
  type: NodePort
  selector:
    app: media-server-calibre-web-template
  ports:
    - name: web-ui
      port: 8083
      targetPort: 8083
      
      protocol: TCP
      
      nodePort: 30883
---
# Source: media-server-chart/charts/jellyseerr-chart/templates/everything.yaml
apiVersion: v1
kind: Service
metadata:
  name: media-server-jellyseerr-service
  namespace: media-server
spec:
  type: NodePort
  selector:
    app: media-server-jellyseerr-template
  ports:
    - name: web-ui
      port: 5055
      targetPort: 5055
      
      protocol: TCP
      
      nodePort: 30505
---
# Source: media-server-chart/charts/lazylibrarian-chart/templates/everything.yaml
apiVersion: v1
kind: Service
metadata:
  name: media-server-lazylibrarian-service
  namespace: media-server
spec:
  type: NodePort
  selector:
    app: media-server-lazylibrarian-template
  ports:
    - name: web-ui
      port: 5299
      targetPort: 5299
      
      protocol: TCP
      
      nodePort: 30529
---
# Source: media-server-chart/charts/prowlarr-chart/templates/everything.yaml
apiVersion: v1
kind: Service
metadata:
  name: media-server-prowlarr-service
  namespace: media-server
spec:
  type: NodePort
  selector:
    app: media-server-prowlarr-template
  ports:
    - name: web-ui
      port: 9696
      targetPort: 9696
      
      protocol: TCP
      
      nodePort: 30969
---
# Source: media-server-chart/charts/qbittorrent-chart/templates/everything.yaml
apiVersion: v1
kind: Service
metadata:
  name: media-server-qbittorrent-service
  namespace: media-server
spec:
  type: NodePort
  selector:
    app: media-server-qbittorrent-template
  ports:
    - name: web-ui
      port: 30900
      targetPort: 30900
      
      protocol: TCP
      
      nodePort: 30900
    - name: torrenting
      port: 30681
      targetPort: 30681
      
      nodePort: 30681
    - name: torrenting-udp
      port: 30681
      targetPort: 30681
      
      protocol: UDP
      
      nodePort: 30681
---
# Source: media-server-chart/charts/radarr-chart/templates/everything.yaml
apiVersion: v1
kind: Service
metadata:
  name: media-server-radarr-service
  namespace: media-server
spec:
  type: NodePort
  selector:
    app: media-server-radarr-template
  ports:
    - name: web-ui
      port: 7878
      targetPort: 7878
      
      protocol: TCP
      
      nodePort: 30787
---
# Source: media-server-chart/charts/sonarr-chart/templates/everything.yaml
apiVersion: v1
kind: Service
metadata:
  name: media-server-sonarr-service
  namespace: media-server
spec:
  type: NodePort
  selector:
    app: media-server-sonarr-template
  ports:
    - name: web-ui
      port: 8989
      targetPort: 8989
      
      protocol: TCP
      
      nodePort: 30898
---
# Source: media-server-chart/charts/bazarr-chart/templates/everything.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-server-bazarr-deployment
  namespace: media-server  
  labels:
    
    network-mode: native
    
spec:
  selector:
    matchLabels:
      app: media-server-bazarr-template
  template:
    metadata:
      labels:
        app: media-server-bazarr-template
    spec:
      restartPolicy: Always

      volumes:
        - name: bazarr-volume-media
          persistentVolumeClaim:
            claimName: download-volume-claim

      containers:
        
        
        - name: media-server-bazarr-container
          image: lscr.io/linuxserver/bazarr:latest

          
          ports:
            - name: web-ui
              containerPort: 6767
              
              protocol: TCP
              
          

          volumeMounts:
            - mountPath: "/movies"
              subPath: "library/movies"
              name: bazarr-volume-media
            - mountPath: "/tv"
              subPath: "library/tv"
              name: bazarr-volume-media
            - mountPath: "/config"
              subPath: "configs/bazarr"
              name: bazarr-volume-media          
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: "America/Toronto"
---
# Source: media-server-chart/charts/calibre-web-chart/templates/everything.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-server-calibre-web-deployment
  namespace: media-server  
  labels:
    
    network-mode: native
    
spec:
  selector:
    matchLabels:
      app: media-server-calibre-web-template
  template:
    metadata:
      labels:
        app: media-server-calibre-web-template
    spec:
      restartPolicy: Always

      volumes:
        - name: calibre-web-volume-media
          persistentVolumeClaim:
            claimName: download-volume-claim

      containers:
        
        
        - name: media-server-calibre-web-container
          image: lscr.io/linuxserver/calibre-web:latest

          
          ports:
            - name: web-ui
              containerPort: 8083
              
              protocol: TCP
              
          

          volumeMounts:
            - mountPath: "/books"
              subPath: "library/calibre"
              name: calibre-web-volume-media
            - mountPath: "/config"
              subPath: "configs/calibre-web"
              name: calibre-web-volume-media          
          env:
            - name: DOCKER_MODS
              value: "linuxserver/mods:universal-calibre"
            - name: OAUTHLIB_RELAX_TOKEN_SCOPE
              value: "1"
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: "America/Toronto"
---
# Source: media-server-chart/charts/jellyseerr-chart/templates/everything.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-server-jellyseerr-deployment
  namespace: media-server  
  labels:
    
    network-mode: native
    
spec:
  selector:
    matchLabels:
      app: media-server-jellyseerr-template
  template:
    metadata:
      labels:
        app: media-server-jellyseerr-template
    spec:
      restartPolicy: Always

      volumes:
        - name: jellyseerr-volume-media
          persistentVolumeClaim:
            claimName: download-volume-claim

      containers:
        
        
        - name: media-server-jellyseerr-container
          image: fallenbagel/jellyseerr:latest

          
          ports:
            - name: web-ui
              containerPort: 5055
              
              protocol: TCP
              
          

          volumeMounts:
            - mountPath: "/app/config"
              subPath: "configs/jellyseerr"
              name: jellyseerr-volume-media          
          env:
            - name: TZ
              value: "America/Toronto"
---
# Source: media-server-chart/charts/lazylibrarian-chart/templates/everything.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-server-lazylibrarian-deployment
  namespace: media-server  
  labels:
    
    network-mode: native
    
spec:
  selector:
    matchLabels:
      app: media-server-lazylibrarian-template
  template:
    metadata:
      labels:
        app: media-server-lazylibrarian-template
    spec:
      restartPolicy: Always

      volumes:
        - name: lazylibrarian-volume-media
          persistentVolumeClaim:
            claimName: download-volume-claim

      containers:
        
        
        - name: media-server-lazylibrarian-container
          image: lscr.io/linuxserver/lazylibrarian:latest

          
          ports:
            - name: web-ui
              containerPort: 5299
              
              protocol: TCP
              
          

          volumeMounts:
            - mountPath: "/media"
              subPath: ""
              name: lazylibrarian-volume-media
            - mountPath: "/config"
              subPath: "configs/lazylibrarian"
              name: lazylibrarian-volume-media          
          env:
            - name: DOCKER_MODS
              value: "linuxserver/mods:universal-calibre|linuxserver/mods:lazylibrarian-ffmpeg"
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: "America/Toronto"
---
# Source: media-server-chart/charts/prowlarr-chart/templates/everything.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-server-prowlarr-deployment
  namespace: media-server  
  labels:
    
    network-mode: native
    
spec:
  selector:
    matchLabels:
      app: media-server-prowlarr-template
  template:
    metadata:
      labels:
        app: media-server-prowlarr-template
    spec:
      restartPolicy: Always

      volumes:
        - name: prowlarr-volume-media
          persistentVolumeClaim:
            claimName: download-volume-claim

      containers:
        
        
        - name: media-server-prowlarr-container
          image: lscr.io/linuxserver/prowlarr:latest

          
          ports:
            - name: web-ui
              containerPort: 9696
              
              protocol: TCP
              
          

          volumeMounts:
            - mountPath: "/config"
              subPath: "configs/prowlarr"
              name: prowlarr-volume-media          
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: "America/Toronto"
---
# Source: media-server-chart/charts/qbittorrent-chart/templates/everything.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-server-qbittorrent-deployment
  namespace: media-server  
  labels:
    
    network-mode: gluetun
    
spec:
  selector:
    matchLabels:
      app: media-server-qbittorrent-template
  template:
    metadata:
      labels:
        app: media-server-qbittorrent-template
    spec:
      restartPolicy: Always

      volumes:
        - name: qbittorrent-volume-media
          persistentVolumeClaim:
            claimName: download-volume-claim

      containers:
        

        - name: media-server-qbittorrent-gluetun
          image: qmcgaw/gluetun
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          
          ports:
            - name: web-ui
              containerPort: 30900
              
              protocol: TCP
              
            - name: torrenting
              containerPort: 30681
              
            - name: torrenting-udp
              containerPort: 30681
              
              protocol: UDP
              

          env:
            # - name: DNS_KEEP_NAMESERVER
            #   value: 'on'

            - name: SHADOWSOCKS
              value: 'off'

            - name: HTTPPROXY
              value: 'off'

            - name: TZ
              value: 'America/Toronto'

            - name: VPN_SERVICE_PROVIDER
              value: 'custom'

            - name: VPN_TYPE
              value: 'openvpn'

            - name: VPN_ENDPOINT_IP
              value: '199.189.26.131'
            
            - name: VPN_ENDPOINT_PORT
              value: '443'

            - name: OPENVPN_USER
              value: '3zk25t6q-8x6aknz'

            - name: OPENVPN_PASSWORD
              value: 'x6fuwh92bk'

            - name: OPENVPN_CUSTOM_CONFIG
              value: '/gluetun/Windscribe-StaticIP.ovpn'

            - name: FIREWALL_INPUT_PORTS
              value: "30900,30681,30681"

            - name: HEALTH_VPN_DURATION_INITIAL
              value: '30s'

          volumeMounts:
            - name: qbittorrent-volume-media
              mountPath: /gluetun
              subPath: 'configs/gluetun'

        
        
        - name: media-server-qbittorrent-container
          image: lscr.io/linuxserver/qbittorrent:latest

          

          volumeMounts:
            - mountPath: "/media/torrents"
              subPath: "torrents"
              name: qbittorrent-volume-media
            - mountPath: "/config"
              subPath: "configs/qbittorrent"
              name: qbittorrent-volume-media          
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: "America/Toronto"
            - name: WEBUI_PORT
              value: "30900"
---
# Source: media-server-chart/charts/radarr-chart/templates/everything.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-server-radarr-deployment
  namespace: media-server  
  labels:
    
    network-mode: native
    
spec:
  selector:
    matchLabels:
      app: media-server-radarr-template
  template:
    metadata:
      labels:
        app: media-server-radarr-template
    spec:
      restartPolicy: Always

      volumes:
        - name: radarr-volume-media
          persistentVolumeClaim:
            claimName: download-volume-claim

      containers:
        
        
        - name: media-server-radarr-container
          image: lscr.io/linuxserver/radarr:latest

          
          ports:
            - name: web-ui
              containerPort: 7878
              
              protocol: TCP
              
          

          volumeMounts:
            - mountPath: "/media"
              subPath: ""
              name: radarr-volume-media
            - mountPath: "/config"
              subPath: "configs/radarr"
              name: radarr-volume-media          
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: "America/Toronto"
---
# Source: media-server-chart/charts/sonarr-chart/templates/everything.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-server-sonarr-deployment
  namespace: media-server  
  labels:
    
    network-mode: native
    
spec:
  selector:
    matchLabels:
      app: media-server-sonarr-template
  template:
    metadata:
      labels:
        app: media-server-sonarr-template
    spec:
      restartPolicy: Always

      volumes:
        - name: sonarr-volume-media
          persistentVolumeClaim:
            claimName: download-volume-claim

      containers:
        
        
        - name: media-server-sonarr-container
          image: lscr.io/linuxserver/sonarr:latest

          
          ports:
            - name: web-ui
              containerPort: 8989
              
              protocol: TCP
              
          

          volumeMounts:
            - mountPath: "/media"
              subPath: ""
              name: sonarr-volume-media
            - mountPath: "/config"
              subPath: "configs/sonarr"
              name: sonarr-volume-media          
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: "America/Toronto"
---
# Source: media-server-chart/charts/bazarr-chart/templates/everything.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: media-server-bazarr-ingress
  namespace: media-server
spec:
  defaultBackend:
    service:
      name: media-server-bazarr-service
      port:
        name: https
  ingressClassName: tailscale
  
  # this sets the hostname for the ingress in tailnet
  tls:
  - hosts:
    - bazarr
---
# Source: media-server-chart/charts/calibre-web-chart/templates/everything.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: media-server-calibre-web-ingress
  namespace: media-server
spec:
  defaultBackend:
    service:
      name: media-server-calibre-web-service
      port:
        name: https
  ingressClassName: tailscale
  
  # this sets the hostname for the ingress in tailnet
  tls:
  - hosts:
    - calibre-web
---
# Source: media-server-chart/charts/jellyseerr-chart/templates/everything.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: media-server-jellyseerr-ingress
  namespace: media-server
spec:
  defaultBackend:
    service:
      name: media-server-jellyseerr-service
      port:
        name: https
  ingressClassName: tailscale
  
  # this sets the hostname for the ingress in tailnet
  tls:
  - hosts:
    - jellyseerr
---
# Source: media-server-chart/charts/lazylibrarian-chart/templates/everything.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: media-server-lazylibrarian-ingress
  namespace: media-server
spec:
  defaultBackend:
    service:
      name: media-server-lazylibrarian-service
      port:
        name: https
  ingressClassName: tailscale
  
  # this sets the hostname for the ingress in tailnet
  tls:
  - hosts:
    - lazylibrarian
---
# Source: media-server-chart/charts/prowlarr-chart/templates/everything.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: media-server-prowlarr-ingress
  namespace: media-server
spec:
  defaultBackend:
    service:
      name: media-server-prowlarr-service
      port:
        name: https
  ingressClassName: tailscale
  
  # this sets the hostname for the ingress in tailnet
  tls:
  - hosts:
    - prowlarr
---
# Source: media-server-chart/charts/qbittorrent-chart/templates/everything.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: media-server-qbittorrent-ingress
  namespace: media-server
spec:
  defaultBackend:
    service:
      name: media-server-qbittorrent-service
      port:
        name: https
  ingressClassName: tailscale
  
  # this sets the hostname for the ingress in tailnet
  tls:
  - hosts:
    - qbittorrent
---
# Source: media-server-chart/charts/radarr-chart/templates/everything.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: media-server-radarr-ingress
  namespace: media-server
spec:
  defaultBackend:
    service:
      name: media-server-radarr-service
      port:
        name: https
  ingressClassName: tailscale
  
  # this sets the hostname for the ingress in tailnet
  tls:
  - hosts:
    - radarr
---
# Source: media-server-chart/charts/sonarr-chart/templates/everything.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: media-server-sonarr-ingress
  namespace: media-server
spec:
  defaultBackend:
    service:
      name: media-server-sonarr-service
      port:
        name: https
  ingressClassName: tailscale
  
  # this sets the hostname for the ingress in tailnet
  tls:
  - hosts:
    - sonarr
