appName: sonarr
imageLocation: lscr.io/linuxserver/sonarr:latest
containerPorts: 
  - name: web-ui
    port: 8989
    targetPort: 8989
    nodePort: 30898
    protocol: TCP
ingress:
  enabled: true
  servicePort: 8989
gluetun:
  enabled: false
  volumeName: media
envVars:
  TZ: America/Toronto
  PUID: 1000
  PGID: 1000
existingVolumes:
  - name: 'media'
    claimName: 'download-volume-claim'
existingVolumeClaims:
  - name: 'media'
    mountPath: '/media'
    subPath: ''
  - name: 'media'
    mountPath: '/config'
    subPath: 'configs/sonarr'