{{- define "media-server-chart.deployment" }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.namespace }}-{{ .Values.appName }}-deployment
  namespace: {{ .Values.global.namespace }}  
  labels:
    {{ if .Values.gluetun.enabled }}
    network-mode: gluetun
    {{ else }}
    network-mode: native
    {{ end }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.global.namespace }}-{{ .Values.appName }}-template
  template:
    metadata:
      labels:
        app: {{ .Values.global.namespace }}-{{ .Values.appName }}-template
    spec:
      restartPolicy: Always

      volumes:
        {{- range $volume := .Values.existingVolumes }}
        - name: {{ $.Values.appName }}-volume-{{ $volume.name }}
          persistentVolumeClaim:
            claimName: {{ $volume.claimName }}
        {{- end }}
        {{- range $volume := .Values.dynamicVolumes }}
        - name: {{ $.Values.appName }}-volume-{{ $volume.name }}
          persistentVolumeClaim:
            claimName: {{ $.Values.global.namespace }}-{{ $.Values.appName }}-claim-{{ $volume.name }}
        {{- end }}

      containers:
        {{ if .Values.gluetun.enabled }}

        - name: {{ .Values.global.namespace }}-{{ .Values.appName }}-gluetun
          image: qmcgaw/gluetun
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          
          ports:
            {{- range $port := .Values.containerPorts }}
            - name: {{ $port.name }}
              containerPort: {{ $port.port }}
              {{ if $port.protocol }}
              protocol: {{ $port.protocol }}
              {{ end }}
            {{- end }}
            {{- range $port := .Values.hostPorts }}
            - name: {{ $port.name }}
              containerPort: {{ $port.port }}
              hostPort: {{ $port.port }}
              {{ if $port.protocol }}
              protocol: {{ $port.protocol }}
              {{ end }}
            {{- end }}

          env:
            # If you can figure out how to keep this on and not lose connectivity
            # please make a PR. Without it there is no service name->IP resolution.
            # - name: DNS_KEEP_NAMESERVER
            #   value: 'on'

            - name: SHADOWSOCKS
              value: 'off'

            - name: HTTPPROXY
              value: 'off'

            - name: TZ
              value: {{ .Values.global.gluetun.TZ | quote }}

            - name: VPN_SERVICE_PROVIDER
              value: 'custom'

            - name: VPN_TYPE
              value: 'openvpn'

            - name: VPN_ENDPOINT_IP
              value: {{ .Values.global.gluetun.endpointIp | quote }}
            
            - name: VPN_ENDPOINT_PORT
              value: {{ .Values.global.gluetun.endpointPort | quote }}

            - name: OPENVPN_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.gluetun.openVpnUserSecretName | quote }}
                  key: {{ .Values.global.gluetun.openVpnUserSecretKey | quote }}

            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.gluetun.openVpnPassSecretName | quote }}
                  key: {{ .Values.global.gluetun.openVpnPassSecretKey | quote }}

            - name: OPENVPN_CUSTOM_CONFIG
              value: {{ .Values.global.gluetun.ovpnFile | quote }}
            
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: '10.152.183.0/24' # swap to match your setup

            - name: FIREWALL_INPUT_PORTS
              value: {{ include "gluetunPorts" . | trimSuffix "," | quote }}

            - name: HEALTH_VPN_DURATION_INITIAL
              value: '30s'

          volumeMounts:
            - name: {{ $.Values.appName }}-volume-{{ $.Values.global.gluetun.volumeName }}
              mountPath: /gluetun
              subPath: 'configs/gluetun'

        {{ end }}
        
        - name: {{ .Values.global.namespace }}-{{ .Values.appName }}-container
          image: {{ .Values.imageLocation }}

          {{ if not .Values.gluetun.enabled }}
          ports:          
            {{- range $port := .Values.containerPorts }}
            - name: {{ $port.name }}
              containerPort: {{ $port.port }}
              {{ if $port.protocol }}
              protocol: {{ $port.protocol }}
              {{ end }}
            {{- end }}
            {{- range $port := .Values.hostPorts }}
            - name: {{ $port.name }}
              containerPort: {{ $port.port }}
              hostPort: {{ $port.port }}
              {{ if $port.protocol }}
              protocol: {{ $port.protocol }}
              {{ end }}
            {{- end }}
          {{ end }}

          volumeMounts:
            {{- range $volume := .Values.existingVolumeClaims }}
            - mountPath: {{ $volume.mountPath | quote }}
              subPath: {{ $volume.subPath | quote }}
              name: {{ $.Values.appName }}-volume-{{ $volume.name }}
            {{- end }}  
            {{- range $volume := .Values.dynamicVolumes }}
            - mountPath: {{ $volume.mountPath | quote }}
              name: {{ $.Values.appName }}-volume-{{ $volume.name }}
            {{- end }}          
          env:
            {{- range $key, $val := .Values.envVars }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}

{{- end }}