{{- define "media-server-chart.ingress" }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.global.namespace }}-{{ .Values.appName }}-ingress
  namespace: {{ .Values.global.namespace }}
spec:
  rules:
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.global.namespace }}-{{ .Values.appName }}-service
              port:
                number: {{ .Values.ingress.servicePort }}

{{- end }}