apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: download-volume-claim
  namespace: {{ .Values.global.namespace }}
spec:
  storageClassName: manual
  volumeName: download-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.downloadStorageAmount }}