apiVersion: v1
kind: PersistentVolume
metadata:
  name: download-volume
  namespace: {{ .Values.global.namespace }}
  labels:
    type: local
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: {{ .Values.downloadStorageAmount }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.downloadLocation | quote }}