appName: bazarr
imageLocation: lscr.io/linuxserver/bazarr:latest
containerPorts: 
  - name: web-ui
    port: 6767
    targetPort: 6767
    nodePort: 30676
    protocol: TCP
ingress:
  enabled: true
  servicePort: 6767
gluetun:
  enabled: false
  volumeName: media
envVars:
  TZ: America/Toronto
  PUID: 1000
  PGID: 1000
existingVolumes:
  - name: 'media'
    claimName: 'download-volume-claim'
existingVolumeClaims:
  - name: 'media'
    mountPath: '/movies'
    subPath: 'library/movies'
  - name: 'media'
    mountPath: '/tv'
    subPath: 'library/tv'
  - name: 'media'
    mountPath: '/config'
    subPath: 'configs/bazarr'