appName: radarr
imageLocation: lscr.io/linuxserver/radarr:latest
containerPorts: 
  - name: web-ui
    port: 7878
    targetPort: 7878
    nodePort: 30787
    protocol: TCP
ingress:
  enabled: false
  servicePort: 7878
envVars:
  TZ: America/Toronto
  PUID: 1000
  PGID: 1000
existingVolumes:
  - name: 'media'
    claimName: 'download-volume-claim'
existingVolumeClaims:
  - name: 'media'
    mountPath: '/media'
    subPath: ''
  - name: 'media'
    mountPath: '/config'
    subPath: 'configs/radarr'